# Site settings
title: Deep Learning For Coders&mdash;36 hours of lessons for free
organization: fast.ai
repository: fastai/dlcert1
email: info@fast.ai
description: > 
  fast.ai's practical deep learning MOOC for coders. Learn CNNs, RNNs, computer vision, NLP, recommendation systems, pytorch, time series, and much more
baseurl: "" # the subpath of your site
url: "http://course18.fast.ai" # the base hostname & protocol for your site
twitter_username: fastdotai
github_username:  fastai

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

# Google services
google_analytics: UA-89522379-1
